src/CPPDataMember.cxx, src/CPPDataMember.h, src/CPPOverload.cxx, src/CPPOverload.h, src/CPPScope.cxx, src/CustomPyTypes.cxx, src/CustomPyTypes.h, src/TemplateProxy.cxx, src/TemplateProxy.h, src/TypeManip.cxx
See my initial issue [here](https://bitbucket.org/wlav/cppyy/issues/339/make-c-documentation-available-to-python). Regarding your [comment](https://bitbucket.org/wlav/cppyy/issues/369/template-instantiation-not-happening-in#comment-61161603):
> I was kindof hoping to find a solution that doesn’t require adding another pointer CPPOverload::MethodInfo_t. Not sure whether that’s possible, though, but the whole structure could be reduced: there need not be a separate dispatch map as a loop over methods would be just as fast and fName is hardly used (only in error reporting and __str__), so could be on-demand instead.
...I took the easy path and did exactly that to `CPPDataMember` (where I could add the member field directly to the class), `TemplateProxy`, and `CPPOverload` (where I added the …
=> make __doc__ of class members writable

src/CustomPyTypes.cxx
Since Python 3.12, in the implementation of 'classobject.h' the function PyMethod_GET_SELF performs an assert to check that the passed function argument is a method:
```
\#define _PyMethod_CAST(meth) \
(assert(PyMethod_Check(meth)), _Py_CAST(PyMethodObject*, meth))
[...]
static inline PyObject* PyMethod_GET_SELF(PyObject *meth) {
return _PyMethod_CAST(meth)->im_self;
}
```
It's fair that the assert fails, because the Python type of `meth` in this context is not a `PyMethod_Type`, but the
`CustomInstanceMethod_Type` from cppyy. However, as can be seen in the implementation of `CustomInstanceMethod_New`, the actual C++ type that implements this custom cppy type is just the regular `PyMethodObject`.
Hence, this commit suggests new assert-free `CustomInstanceMethod_GET_*` macros that replace …
=> Prevent `cppyy.InstanceMethod` from crashing due to Python 3.12 asserts

src/SignalTryCatch.h
By default, the `ExceptionContext_t` class is expected in the namespace `CppyyLegacy`, If it is expected in no namespace, one can explicitly define `NO_CPPYY_LEGACY_NAMESPACE` at build time (e.g. if one wants to use ROOT as a backend).
=> Make `CppyyLegacy` namespace in CPyCppyy optional

src/CPPMethod.cxx, src/Cppyy.h
- **Port of https://github.com/root-project/root/pull/9092**
- **Corresponding cppyy-backend PR: https://github.com/wlav/cppyy-backend/pull/20**
---------------------
The current implementation of the CPPMethod::GetPriority function considers only direct bases of the class type given as input parameter to a certain function. This can lead to situations which are easily distinguishable but that lead to the same overload being called when passing instances of different classes of the same inheritance tree.
For example,
```python
import ROOT
ROOT.gInterpreter.Declare(
'''
class A {};
class B: public A {};
class C: public B {};
void myfunc(const B &b){
std::cout << "B" << std::endl;
}
void myfunc(const C &c){
std::cout << "C" << std::endl;
}
''')
ROOT.myfunc(ROOT.B())
ROOT.myfunc(ROOT.C()) …
```
=> Improve priority assignment of classes in same inheritance tree

src/CPPMethod.cxx
Given the following function declared to cppyy and accessed via a Python proxy:
```c++
int foo(int x);
```
Currently accessing its `func_doc`, which in turn calls `CPPMethod::GetPrototype`, gives:
'int ::foo(int x)'
The extra set of '::' can be avoided by checking that the function is not declared inside a namespace.
See also the corresponding ROOT PR:
https://github.com/root-project/root/pull/11413
Cudos goes to @vepadulano, the original author of this commit.
=> Improve output of `CPPMethod::GetPrototype`

src/Converters.cxx, src/Converters.h, src/DeclareConverters.h
There are two possible fixes to the problem with string lifetimes and `std::string_view` arguments:
* setting a lifeline
* copying the string
Copying the string is supposedly faster on average, at least in the ROOT usecase the strings that are passed around are not very long (RDataFrame filter and variable definitions).
Also, the `InitializerListConverter` is changed such that it creates separate converters for each element if the converters have state.
This PR fixes the following reproducer:
```Python
If they have state, a separate converter needs to be created for each
element in the initializer list.
Fixes the following reproducer:
```python
import cppyy
cppyy.cppdef("""
void foo(std::string_view s1, std::string_view s2)
{
std::cout << s1 << std::endl;
std::cout << s2 << std::endl; …
=> Carry a copy of the string also in the `std::string_view` converter and consider statefulness in `InitializerListConverter`

src/Utility.cxx
The inconsistent types were also observed on 32-bit Linux.
In ROOT, this was hotfixed by adding a check for 32-bit Linux in the
preprecessor check, but this required including `RConfig.h`. I don't
think this is desirable.
A better and more direct check for the underlying problem case is to
check if `long int` and `int` have the same size.
This is part of the effort to reduce the differences between PyROOT and
upstream CPyCppyy.
Related commits:
* https://github.com/wlav/CPyCppyy/commit/8a72866
* root-project@02251b5
=> Improve integer type checking in `Utility::GetBuffer()`

src/API.cxx, src/CPPClassMethod.cxx, src/CPPDataMember.cxx, src/CPPExcInstance.cxx, src/CPPInstance.cxx, src/CPPInstance.h, src/CPPOverload.cxx, src/CPPScope.cxx, src/CPyCppyyModule.cxx, src/CallContext.h, src/Converters.cxx, src/CustomPyTypes.cxx, src/Executors.cxx, src/LowLevelViews.cxx, src/MemoryRegulator.cxx, src/ProxyWrappers.cxx, src/Pythonize.cxx, src/TemplateProxy.cxx, src/TupleOfInstances.cxx, src/TypeManip.cxx, src/Utility.cxx
Also fix the typos found with:
https://github.com/crate-ci/typos
Validated by the ROOT sync PR:
https://github.com/root-project/root/pull/14507
=> Fix incomplete initializer lists, unused vars, and some type warnings

src/CPPDataMember.cxx, src/CPPExcInstance.cxx, src/CPPInstance.cxx, src/CPPOverload.cxx, src/CPPScope.cxx, src/CPyCppyyModule.cxx, src/CustomPyTypes.cxx, src/LowLevelViews.cxx, src/TemplateProxy.cxx, src/TupleOfInstances.cxx
Adapting to a new field in Python 3.12:
https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_watched
Corresponding ROOT PR: https://github.com/root-project/root/pull/15072
=> Fix `missing-field-initializers` with Python 3.12

include/CPyCppyy/API.h, src/Converters.cxx, src/Converters.h, src/Executors.cxx, src/Executors.h
It would be nice to be able to define custom executors and converters that are just referencing existing ones.
That would for example help to support the legacy ROOT types without having to patch CPyCppyy:
* https://github.com/root-project/root/pull/15788
=> Extend API to define executor and converter aliases

src/Executors.cxx
::operator delete only frees the memory that was previously allocated in Cppyy::CallO, but does not call the destructor of the std::string. Make sure that is done using keyword delete.
This is part of a fix in ROOT that also applies to CPyCppyy:
https://github.com/root-project/root/pull/15777
=> Destroy STL string objects in STLWStringExecutor

src/Converters.cxx
Closes https://github.com/wlav/cppyy/issues/221, if the change in memory policy was accidental.
This fixes the memory test in the synchronization PR:
https://github.com/root-project/root/pull/14507
=> Correcly forward `control` flag to InstancePtrConverter

src/PyException.cxx
This can happen for example with jitted code, and would lead to this ugly printout otherwise:
```
python exception (at :0 )
```
Maybe a bit pedantic, but our unit tests in ROOT were testing for the exact wording, which is why I suggest to fix this.
=> Don't attempt to print detailed exception info if filename is empty

src/API.cxx
Two implementations are provided, i.e. for Python versions older than 3.8, for which PEP 587 is not in force, and newer.
Credit goes to Danilo Piparo (@dpiparo), who originally made this change for ROOTs TPython:
https://github.com/root-project/root/pull/13532
I have verified that with this PR and PR #30, the ROOT unit test for `TPython::ExecScript` also works with `CPyCppyy::ExecScript`, bringing us one step closer to phasing out TPython:
https://github.com/root-project/roottest/blob/master/python/tpython/execscript.C
=> Implement TPython::ExecScript for Python 3

src/API.cxx
The `gMainDict` should be borrowed, i.e. we are not calling Py_INCREF(gMainDict). Like this, we avoid unexpectedly affecting how long `__main__` is kept alive. The `gMainDict` is only used in `Exec()`, `ExecScript()`, and `Eval()`, which should not be called after `__main__` is garbage collected anyway.
Equivalent ROOT PR with the CI run:
https://github.com/root-project/root/pull/16403
=> Avoid holding reference to `__main__` in the CPyCppyy API

src/TypeManip.cxx
Prevents illegal function names in generated code stitched together by the [aggregate initializer](https://github.com/wlav/CPyCppyy/blob/ecd1d0c350761d7bbd7d0f670293d82137f51b79/src/Pythonize.cxx#L1719)
See related PR with the failing tests: https://github.com/root-project/root/pull/16338/
=> Drop `*` in `TypeManip` when changing scope to legal name

src/CPPInstance.cxx, src/CPyCppyyModule.cxx, src/Executors.cxx, src/Pythonize.cxx
No static `gPythonizations` variable to avoid static initialization order fiasco. This avoids some crashes when using `TPython` in compiled code.
This is necessary to make a newly suggested TPython multithreading unit test work:
https://github.com/root-project/root/pull/16427
=> No static gPythonizations variable to avoid initialization order fiasco

src/CPPClassMethod.h, src/CPPConstructor.h, src/CPPFunction.h, src/CPPGetSetItem.h, src/CPPMethod.h, src/CPPOperator.h, src/Converters.h, src/DeclareConverters.h, src/DeclareExecutors.h, src/Executors.h, src/TemplateProxy.cxx
In ROOT we just had a campaign to use the `override` keyword where possible:
* https://github.com/root-project/root/pull/18918
I guess it would be good to do the same thing here.
=> Add missing `override` keywords

src/CPPMethod.cxx
In `CPPMethod::Call`, the number of positional arguments might be mutated by the `ProcessArgs(cargs)` invocation, which might transfer keyword args to positional args. The updated number of positional arguments will be stored as the `cargs.fNArgsf` data member, which should be used in the rest of the `Call()` implementation instead of the original `nargsf`.
Fixing this logical mistake fixes some problems, like the reproducer in issue root-project#16406 with Python versions before Python 3.11.
Taken from the following ROOT PR: https://github.com/root-project/root/pull/19146
=> Fix logic error in CPPMethod::Call with keyword arguments

src/Pythonize.cxx
When checking if a class has the `size()` method implemented in the style of the STL, the attribute must be a CPyCppyy overload. Otherwise the check gives false positives in the case where the class has a non-function attribute that is called "size".
This problem was caught in the Python debug interpreter.
Upstream version of https://github.com/root-project/root/pull/19240.
=> Avoid false positives in `size()` pythonization

src/CPPOverload.cxx, src/CPyCppyyModule.cxx
The `_Py_HashPointer` function was deprecated in Python 3.13 because it was promoted to be part of the stable API. Using the stable API version for Python >= 3.13 avoids build warnings.
=> Avoid using deprecated `_Py_HashPointer` function
